name: dream_diary
description: A beautiful diary app with creative UI

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2  # Add this if using iOS-style icons
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  google_fonts: ^4.0.4
  liquid_pull_to_refresh: ^3.0.0
  confetti: ^0.7.0
  shimmer: ^2.0.0
  flutter_staggered_animations: ^1.1.0
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/diary_bg.jpeg  # Fixed path